### ISSUE TITLE
row selection

### ISSUE THREAD

**Issue by johnv02139** [tvrenamer/tvrenamer#105]
The current version of the main table allows single selection (one row at a time), with "full selection" of rows.  Each row also has a check-box.  The check-box determines whether or not the file in the row should get renamed or not.  So, it's not clear to me what the selection does.  It doesn't seem to ever make any difference which row is selected.  Am I mistaken about that?

A very trivial change allows multiple selection: shift-click selects continuous rows, control-click allows discontinuous rows to be selected, etc.

But, again, being selected currently means nothing.  I think the best change would be to keep the check boxes, and have them be what determines which get changed; which rows are selected at the time the button is clicked will continue to mean nothing.  However, if you select multiple rows, and click the check box of any one of the selected rows, the new state of the row you've clicked on, will apply to all selected rows.  Non-selected rows will not be affected.

Does that sound like the right behavior?

(An alternate approach would be to eliminate the check boxes altogether, and let row-selection be what determines which files to rename.  But I think that's inferior.)

I also would like to add buttons at the top for "select all" and "deselect all".  Let me know what you think, or I can just send you the pull request later so you could see it.

Thanks.

**Comment by eprenamer** [comment]
This was resolved by #110
