### ISSUE TITLE
whitespace in source files

### ISSUE THREAD

**Issue by johnv02139** [tvrenamer/tvrenamer#107]
I found that most of the indentation in the files I looked at was hard tabs.  I definitely prefer spaces, but I'm willing to go with existing conventions.  But it was not consistent -- a lot of lines did have spaces instead of tabs.  Then I noticed your Wiki says "never allow tabs in any source code".

I could probably run a formatter over the whole code base to remove all the tabs.  The irritating part about doing this is that it shows up as an enormous diff, and may cause spurious conflicts with other branches.  On the other hand, github's tools should be able to let you see that the non-whitespace diffs are zero, and I don't think there are really any other active development branches.

**Comment by johnv02139** [comment]
I used Google's code formatter in my fork, which changed way too much.  Unfortunately a lot of the edits I made was *after* I had done that, but that's my problem.

However, I really really do want to be rid of the tabs.  If I requested a pull for a change which did nothing but replace each tab with four spaces, would you take it?

**Comment by vipuldelwadia** [comment]
I prefer tabs to spaces, but more than that I would like the whitespace to be consistent, so yep I'll merge a pull request which fixes up the formatting :)
