### ISSUE TITLE
improve handling of punctuation and camel case

### ISSUE THREAD

**Issue by johnv02139** [tvrenamer/tvrenamer#108]
I've found some issues with how punctuation is handled.

For some punctuation that is found within a word, it's much better to remove it, than to replace it with a space.  For example, "Bob's Burgers" should become "Bobs Burgers", not "Bob s Burgers"

Interestingly I had a problem even with the example given.  It works great with "Marvels.Agents.of.S.H.I.E.L.D." but not with "Marvel's Agents of S.H.I.E.L.D."

I think trying for one big do-it-all regex is probably too complicated.  I have a proposed fix that handles a few cases one at a time.

**Comment by eprenamer** [comment]
Resolved in #119
