### ISSUE TITLE
testRegex ?

### ISSUE THREAD

**Issue by johnv02139** [tvrenamer/tvrenamer#109]
In [FilenameRegexTest.java](https://github.com/tvrenamer/tvrenamer/blob/master/src/test/com/google/code/tvrenamer/FilenameRegexTest.java#L39), there is a test that runs over several filenames, attempting to match each one to a regex.  But if it doesn't match, the test doesn't fail, it just prints a message to stdout.

I find that a number of them produce "no match".  Is there possibly something wrong with my setup, or do these produce "no match" for you, as well?

    [junit] 24.s08.e01.720p.hdtv.x264-immerse.mkv -> no match
    [junit] 24.S07.E18.720p.BlueRay.x264-SiNNERS.mkv -> no match
    [junit] human.target.2010.s01.e02.720p.hdtv.x264-2hd.mkv -> no match
    [junit] dexter.407.720p.hdtv.x264-sys.mkv -> no match
    [junit] JAG.S10E01.DVDRip.XviD-P0W4DVD.avi -> JAG [10x01]
    [junit] Lost.S06E05.Lighthouse.DD51.720p.WEB-DL.AVC-FUSiON.mkv -> Lost [6x05]
    [junit] warehouse.13.s1e01.720p.hdtv.x264-dimension.mkv -> warehouse 13 [1x01]
    [junit] one.tree.hill.s07e14.hdtv.xvid-fqm.avi -> one tree hill [7x14]
    [junit] gossip.girl.s03e15.hdtv.xvid-fqm.avi -> gossip girl [3x15]
    [junit] smallville.s09e14.hdtv.xvid-xii.avi -> smallville [9x14]
    [junit] smallville.s09e15.hdtv.xvid-2hd.avi -> smallville [9x15]
    [junit] the.big.bang.theory.s03e18.720p.hdtv.x264-ctu.mkv -> the big bang theory [3x18]
    [junit] castle.2009.s01e09.720p.hdtv.x264-ctu.mkv -> castle 2009 [1x09]
    [junit] Marvels.Agents.of.S.H.I.E.L.D.S03E03.HDTV.x264-FLEET -> Marvels Agents of SHIELD [3x03]

**Comment by lsrom** [comment]
I just noticed it and in my case the number of no matches is even higher. Is it something that has been broken by recent changes maybe? I tried to run earlier version (from before pull req #115 was accepted and it works with filenames from the list I randomly tested.  

My output of the test looks like this: 

```
24.s08.e01.720p.hdtv.x264-immerse.mkv -> no match
24.S07.E18.720p.BlueRay.x264-SiNNERS.mkv -> no match
human.target.2010.s01.e02.720p.hdtv.x264-2hd.mkv -> no match
dexter.407.720p.hdtv.x264-sys.mkv -> no match
JAG.S10E01.DVDRip.XviD-P0W4DVD.avi -> no match
Lost.S06E05.Lighthouse.DD51.720p.WEB-DL.AVC-FUSiON.mkv -> Lost [6x05]
warehouse.13.s1e01.720p.hdtv.x264-dimension.mkv -> warehouse 13 [1x01]
one.tree.hill.s07e14.hdtv.xvid-fqm.avi -> no match
gossip.girl.s03e15.hdtv.xvid-fqm.avi -> no match
smallville.s09e14.hdtv.xvid-xii.avi -> no match
smallville.s09e15.hdtv.xvid-2hd.avi -> no match
the.big.bang.theory.s03e18.720p.hdtv.x264-ctu.mkv -> the big bang theory [3x18]
castle.2009.s01e09.720p.hdtv.x264-ctu.mkv -> castle 2009 [1x09]
Marvels.Agents.of.S.H.I.E.L.D.S03E03.HDTV.x264-FLEET -> no match
```

**Comment by vipuldelwadia** [comment]
Aha! You've discovered a skeleton in our closet :)

In short, that test is not really useful, as it only tries to match against the second regex in the list. Also, it was written by a less-wise, naïver Java dev (me about 5 years ago).

**Comment by vipuldelwadia** [comment]
I've just fixed up that test with commit eb15c8
