### ISSUE TITLE
java package

### ISSUE THREAD

**Issue by johnv02139** [tvrenamer/tvrenamer#122]
I assume that the reason the code is in the com.google package is because it was started for Google's summer of code, or some similar event.  But it really doesn't make much sense any more, does it?  And you guys have the tvrenamer.org domain.  Is there a reason you don't move the code into the org.tvrenamer package?

Thanks.

**Comment by lsrom** [comment]
This could potentially break git version history. Meaning we wouldn't be able to merge new code from our repositories without making new fork. I might be wrong about this though in which case I am all for it.

**Comment by johnv02139** [comment]
Well, it shouldn't break git version history, exactly.  Git understands "moving" a file.  But yeah, it does present issues with existing, unmerged code.  We could have a little script that could move any branch to this style.

**Comment by vipuldelwadia** [comment]
Yeah the project used to be on google code, and so we packaged the Java as google code.

I think `org.tvrenamer` is a suitable package now.

As for breaking history, @johnv02139 is correct in that git will follow the files. Sometimes it won't automatically follow them, so you can force it on the command line (`--follow`) and the various git clients have options for following renames.
