### ISSUE TITLE
Clean up useless code

### ISSUE THREAD

**Issue by lsrom** [tvrenamer/tvrenamer#123]
I noticed TVRage is gone so class `com.google.code.tvrenamer.controller.TVRageProvider` and all associated code (if there is one) is useless.

I propose we remove it and perhaps add TVMAZE as mentioned in #89 if required.  

Also, #21 can be closed as well, since alternative to TVRage is implemented and working. Comments mention possibility of language selection which is not implemented but if there is demand for such feature I think it deserves own issue.

**Comment by vipuldelwadia** [comment]
I agree, fell free to make a pull request which removes the old / dead code. Anything we can do to help the navigability the better!

**Comment by eprenamer** [comment]
Resolved in #145
