### ISSUE TITLE
make two separate steps: find show and find episode

### ISSUE THREAD

**Issue by johnv02139** [tvrenamer/tvrenamer#129]
There are really two distinct steps to parsing a filepath: (1) identify the show; (2) identify the episode, which must be an episode of the found show.

Of course, those two steps also have substeps, e.g.:
(1a) extract the portion of the file path that we think identifies the show
(1b) query for that text at thetvdb.com
(1c) parse resulting XML from thetvdb.com
(1d) choose result from XML (currently, we always choose the first result, but that could potentially change)

Anyway, the real point is that it's possible to succeed in finding the show, but fail to find the episode; or, to find a show (incorrectly), and be unable to find the episode because we're looking for the wrong show.

I think the UI should reflect this more.  Rather than just generic failure, I think it should be able to report, "could not find show", or "found show but could not find episode".

Again, this is something I've already done in my fork, that I could pull out and integrate into the current master, if it's something you like.

**Comment by eprenamer** [comment]
Resolved in #192 and earlier PRs
