### ISSUE TITLE
Some Shows Won't Download

### ISSUE THREAD

**Issue by solomonj1963** [tvrenamer/tvrenamer#133]
I'm finding some shows stay stuck "downloading".  After reviewing my files, it seems that all the ones that fail have potentially problematic characters in the show name.  I definitely have a lot of Marvel shows for my nephew that all begin in TheTVDB with "Marvel's".  I'm suspecting the apostrophe character may be what isn't processing right.  The TheTVDB entries are exact and do contain the apostrophes.  I'm running on MacOS 10.12.3.

**Comment by daveharris** [comment]
Hi,
Sorry for the late response. We have fixed this (in #108) in an upcoming release. Given that there other people having the same issue we might push out this fix sooner

Dave

**Comment by eprenamer** [comment]
Version 0.8 has been released, I believe this is resolved.  Closing.  ( @solomonj1963 please feel free to re-open if you believe the problem persists in version 0.8 )
