### ISSUE TITLE
Is it down?

### ISSUE THREAD

**Issue by Spaceherpe** [tvrenamer/tvrenamer#136]
Lately, I've been getting a time-out error or can't find file name error. When I try to run it again, it will give me the option to change everything but leave the file name missing. (i.e. show name - S01E01 - NOTHING HERE)

**Comment by daveharris** [comment]
Can you explain more what your problem is? Does the application need to handle it better when tvdb.com is down, or do we need do something different after we say that it's down?

**Comment by eprenamer** [comment]
We've made a lot of improvements in version 0.8 to give the user a lot more information.  I'm going to close this.  @Spaceherpe , please feel free to re-open, or to open a new issue, if you still see problems.
