### ISSUE TITLE
use Java 8 time

### ISSUE THREAD

**Issue by eprenamer** [tvrenamer/tvrenamer#143]
The original implementation of java.util.Date left much to be desired.  A third-party package, Joda time, became very popular.  As of Java 8, this is integrated into the Java core packages, with classes like LocalTime.

I've integrated these into my branch.  This does require Java 8, though.  Let me know if you'd like to have these changes.

**Comment by vipuldelwadia** [comment]
Java 7 has been deprecated for 2 years now (https://java.com/en/download/faq/java_7.xml), so I think we are safe to require the Java 8 runtime.

You should make a pull request which contains the Java 8 time change as well as necessary build changes (if any) to require Java 8.

**Comment by eprenamer** [comment]
Awesome.  Will obviously be easier if you can take my PRs in order.  If you really want them out of order, let me know.  Otherwise, I'll get it ready on top of the checkstyle change.

**Comment by vipuldelwadia** [comment]
I'll definitely merge them in order, no point in creating extra meaningless work 😄

**Comment by eprenamer** [comment]
OK.  Well I saw someone else had opened an issue to remove TVRage, and that was the first thing in my branch, and that file actually does use dates, and there's no point to fixing that file to use LocalDate.  So, once the TVRage deletion has been merged, I'll submit this PR on top of it.

**Comment by eprenamer** [comment]
Resolved in PR #146
