### ISSUE TITLE
Rename fail on network share

### ISSUE THREAD

**Issue by daveharris** [tvrenamer/tvrenamer#16]
Select all episodes from a network share and an error is written to stdout.

Expected to see in the column proposed name the filename accordingly to the mask but instead I see the original filename and the error 
`00:24:41,968 DEBUG TVRenamer:50 - fail`
as many times as there are files.

I'm using version 0.2 in Windows XP

**Comment by eprenamer** [comment]
I think the issue here is simply that applications may lock a file while they're reading from them.  I don't really think it has anything to do with the network; the same can happen even on a local disk.  This is just a behavior of Windows and not our issue.
