### ISSUE TITLE
screenshot in Readme no longer working

### ISSUE THREAD

**Issue by eprenamer** [tvrenamer/tvrenamer#180]
It appears the screenshot referred to a dropbox location that is no longer functioning.

**Comment by daveharris** [comment]
That's my bad, I didn't realise that it was being referenced from my Dropbox account and I did a cleanup recently.

I have tried to re-upload the screenshot from https://raw.githubusercontent.com/wiki/tvrenamer/tvrenamer/tvrenamer-0.5b2.png as `https://dl.dropboxusercontent.com/u/554441/Screenshots/tvrenamer-0.7.png` but Dropbox has changed it's public URL scheme and it's now `https://www.dropbox.com/s/u62m9hxej9bvl2o/tvrenamer-0.7.png` so it doesn't match ...

So we need to update `README.md` to reference `https://raw.githubusercontent.com/wiki/tvrenamer/tvrenamer/tvrenamer-0.5b2.png` directly

**Comment by eprenamer** [comment]
OK, I changed it to the path you gave and it seems fine now.
