### ISSUE TITLE
Performance issue with long running daily series

### ISSUE THREAD

**Issue by daveharris** [tvrenamer/tvrenamer#19]
#### What steps will reproduce the problem?
1. Create a file with path .../Neighbours/neighbours.s23e233.pdtv.xvid-ss.txt
2. Select file in browse window of TVRenamer

TVRenamer takes approximately 2 minutes to download and parse the listing of 5700+ episodes.
A download of the same listing takes less than 15 seconds.

Is there any possibility to speed the parsing process up? Multithreading?

**Comment by eprenamer** [comment]
I'm going to close this in favor of #144 .  The new API should be a lot faster.  If it still isn't fast enough, surely whatever issues there are will be unrelated, and we'll deal with them going forward.  :-)
