### ISSUE TITLE
what was situation with Drag and Drop error?

### ISSUE THREAD

**Issue by eprenamer** [tvrenamer/tvrenamer#196]
There is code in UIStarter.java, in the top-level loop, which catches an IllegalArgumentException and warns the user that Drag and Drop is not supported:

https://github.com/tvrenamer/tvrenamer/blob/master/src/main/org/tvrenamer/view/UIStarter.java#L605-L608

This seems like kind of an unusual assumption for an IllegalArgumentException.  Is there any more background on this?  Where was drag-and-drop not supported?  Linux?  Is there no better way to catch the problem?

**Comment by vipuldelwadia** [comment]
I cannot for the life of me remember why / when this would happen. Perhaps older versions of SWT didn't support drag-and-drop on some platforms? Or maybe it only worked on newer Java versions?

At any rate, I think we can just drop that catch block?

**Comment by eprenamer** [comment]
Yeah, if we drop it, an IllegalArgumentException just falls through to the more generic case.

**Comment by eprenamer** [comment]
This is resolved by PR #197
