### ISSUE TITLE
Supported input filenames (Was: "Episode number matching issues with long running daily series.")

### ISSUE THREAD

**Issue by daveharris** [tvrenamer/tvrenamer#20]
#### What steps will reproduce the problem?
1. Create a file with path .../Neighbours/neighbours.s23e233.pdtv.xvid-ss.txt
2. Select file in browse window of TVRenamer
#### What is the expected output? What do you see instead?

The expected proposed name will be `Neighbours [23x223] Episode 5343.txt`
The resulting proposed name is `Neighbours [23x23] Ned Man Walking.txt`

**Comment by eprenamer** [comment]
Three digit episodes have been supported for some time; added a test for the specific example mentioned in the OP.

This issue also mentions episodes with dates but no specific episode numbers; we have #233 for that.
