### ISSUE TITLE
UI reports "Downloading..." when show not found

### ISSUE THREAD

**Issue by eprenamer** [tvrenamer/tvrenamer#212]
If we examine a filename, and find a show name (or what we believe to be a show name) and query the provider for that show name, and get zero results, the UI continues to report the status of the file as "Downloading...".  That's really not accurate, and not good feedback.  It should show a better message.

**Comment by eprenamer** [comment]
This has been resolved, over several commits, notably d5e24d8.  It now reports, "Unable to download show information."

**Comment by daveharris** [comment]
Is it possible to display "Unable to *find* show information." as "unable to download" makes it sound like the internet connection failed or something similar?

**Comment by eprenamer** [comment]
Sure!

**Comment by eprenamer** [comment]
Changed the message in PR #219
