### ISSUE TITLE
Can't find show (date based or episodes in 100's maybe)

### ISSUE THREAD

**Issue by mannynzau** [tvrenamer/tvrenamer#223]
Hi,

Works great with just about everything you can throw at it, with the exception of The Daily Show.

For example:

The.Daily.Show.2017.05.10.Valerie.Jarrett.HDTV.x264

It's by date, so I don't think there is an easy or straightforward way of doing this. So I've manually added in the S and E, but it doesn't seem to recognise episodes in the hundreds, so:

The.Daily.Show.S22E105.D.L.Hughley.HDTV.x264

Comes back for the details for S22E10 (not E10**5**).

Any ideas or suggestions?

Thanks again for the great program!

**Comment by eprenamer** [comment]
Hi, thanks for the feedback.  Unfortunately that's a real limitation right now.  We are prepping a 1.0b1 release.  I'll see if we can get three-digit episode numbers in, for that.

I do expect to handle dates, but not until the next release.

**Comment by eprenamer** [comment]
OK, this should be included in 1.0b1.

**Comment by mannynzau** [comment]
Excellent!! Thanks for getting back so quickly too! 👌🏽

- Manny

**Comment by eprenamer** [comment]
Included in latest 1.0b1 release.

https://github.com/tvrenamer/tvrenamer/releases/tag/v1.0b1

**Comment by eprenamer** [comment]
@mannynzau Now fixed in v0.8

https://github.com/tvrenamer/tvrenamer/releases/latest
