### ISSUE TITLE
internet connection error

### ISSUE THREAD

**Issue by vishalpatel84** [tvrenamer/tvrenamer#239]
When i try to rename an episode i am getting an error, " Downloading show listings failed, Check internet connection". The thing is, my internet is working perfectly.

**Comment by eprenamer** [comment]
The error messages are not that informative.  They will be a lot better in the next release, which is due out soon.  In the mean time, can you give us one or more examples of a filename that is giving you that message?

(You also could pick up a prerelease here:
https://github.com/tvrenamer/tvrenamer/releases/tag/v1.0b3
)

**Comment by vishalpatel84** [comment]
sure, 

Madam.Secretary.S03E23.720p.HDTV.x264-AVS

silicon.valley.s04e05.1080p.web.h264-tbs

- Vishal

**Comment by eprenamer** [comment]
Well, what's happening is the response we get from the provider we use (www.thetvdb.com) is being truncated.

We actually are still on their "old" API, and they're encouraging everyone to upgrade, but we wanted to do one more release before plunging in.

I will try to get in touch with them and see what has changed.  It's possible there's something we can do in our code, too, but I'm not sure, and certainly there's nothing we can do to make already-released versions of the app work, unless thetvdb will revert whatever caused this change.

@vipuldelwadia @daveharris  the app would appear to be totally broken until this is fixed on one end or the other

**Comment by vishalpatel84** [comment]
I tried it a few times, and sometimes i will clear up the name but without the episode name and sometimes with the error, and on the 1 time it will actually do it correctly. 

@eprenamer  thanks for digging into this for me, much appreciated.

**Comment by eprenamer** [comment]
The indication from the forums at thetvdb.com is that they will fix it, but no timetable as of yet.

**Comment by eprenamer** [comment]
This was a transient error with an external resource beyond our control.

The one aspect of it that is within our control is to upgrade the application to use the new API.  We have an issue for that, #144 

The old API at thetvdb.com appears to be working again, for now, so I'm going to close this.
