### ISSUE TITLE
Perform caching of XML

### ISSUE THREAD

**Issue by daveharris** [tvrenamer/tvrenamer#24]
Currently when a file is renamed the XML is downloaded that contains all the episode details and we parse that. 
What would be really nice is to have per-instance caching of the xml.  For example if you rename on House episode and rename another House episode the xml is downloaded twice.  This is both slow and time consuming.

An added feature would be to have a cache of all the xml downloaded for the length the application is running.  We could either roll our our (probably easier and faster) or look at using an established cache in Java like ehcache.

**Comment by eprenamer** [comment]
@daveharris Do you recall what your comment refers to?  What was released in v0.5?

**Comment by daveharris** [comment]
Hi @eprenamer,
This is a bit confusing as this thread was migrated (by hand!) from the old Google Code site before it was shuttered so the authors of the comments had been lost :(

I assume that this was implemented and released, but it was so long ago that I can’t remember. What does it do now if you had 2 episodes of the same show one after another?!

Sorry I can’t be more helpful

**Comment by eprenamer** [comment]
Hi @daveharris , that's actually very helpful.  Until you clarified with that question, I didn't realize what was meant by "per-session caching".  Yes, it does keep the information in memory, and in fact there is code to try to make sure we don't download the same information twice during the same session.  I will re-close this.  We have #121 for longer-term caching.
