### ISSUE TITLE
do minor release?

### ISSUE THREAD

**Issue by eprenamer** [tvrenamer/tvrenamer#242]
As we've discussed, I think version 1.0 should use the TVDB v2 API.  Although it's already working, I think it will take some time to feel confident in it.

Therefore, I think we should put out a 0.8 release.

What I'm suggesting will be basically what we had intended to be 1.0 -- still using the TVDB v1 API.  But I do want to pull out the "numbering scheme" stuff.

**Comment by eprenamer** [comment]
https://github.com/tvrenamer/tvrenamer/releases/tag/v0.8b1

**Comment by vipuldelwadia** [comment]
Cool, I grabbed it and did some quick testing, looks alright to me 👍

Just a quick note that the `tvrenamer.version` inside that tag still says 1.0b3: https://github.com/tvrenamer/tvrenamer/blob/v0.8b1/src/main/tvrenamer.version - just something to be aware of. We can fix it up for the next / final version of 0.8.

**Comment by eprenamer** [comment]
OK, so I think what happened was I created the tag incorrectly.  I did change the version in the branch:

https://github.com/tvrenamer/tvrenamer/blob/v0.8/src/main/tvrenamer.version

... and the binaries I uploaded were from that branch.  But the tag is probably forked off of master.

I will make a new release, 0.8b2, and get it right.

**Comment by eprenamer** [comment]
OK, new pre-release is drafted:

https://github.com/tvrenamer/tvrenamer/releases/tag/v0.8b2

I did base it off of the correct branch, this time.

**Comment by eprenamer** [comment]
One more change I want to make is to the README for #238 .  You can see what the revised README will look like, here:

https://github.com/eprenamer/tvrenamer/tree/deprecation

So if everything looks ok in v0.8b2, I will do one more build, with the updated README, and an updated version.  What version should it be?  Something like "v0.8r0"?  Or v0.8b3?

I will mark the release as NOT a prerelease, and I assume that it will become "latest" on the releases page.

**Comment by vipuldelwadia** [comment]
I think the last time I grabbed one of the 0.8 betas I didn't actually get
the virus issue. I'll have another look tonight and let you know if it's
happening on this build.

For the final release of 0.8, the version should simply be `0.8`, and the
tag `v0.8`

**Comment by eprenamer** [comment]
A 0.8 release is now available.  I submitted a PR to change the tvrenamer.org website.

**Comment by eprenamer** [comment]
Everything is updated on the website.  Closing.
