### ISSUE TITLE
Versions folder upon move

### ISSUE THREAD

**Issue by megavolkan** [tvrenamer/tvrenamer#259]
I'm using tvrenamer for renaming and moving both tv show file and subtitle files. After upgrading to v0.8 tvrenamer started creating a folder called "versions" automatically and appending a "~2" to the end of the subtitle filename. (I'm using only a single sub file). Why is this happening? There is no option under preferences corresponding to this...

**Comment by nextSAK** [comment]
Have the same issue.
a ~2 appending to the end of the sub name.

**Comment by eprenamer** [comment]
Sorry for the late reply.  Yes, that's new behavior, and I understand why it may not be desirable.

What is happening is that there are -- or, at least, it thinks there are -- two or more versions of the same episode.  That is, two or more files that should have the exact same pathname.

So, first thing is, is that actually the case?  If not, then there's a bug, and I can try to look into it (though more information would obviously be helpful).

If that is the case, and you just don't like the behavior, again, that's reasonable.  But what would you like it to do?  You are correct to say that this didn't happen in previous versions, but in fact previous versions could end up overwriting a file, which I think is worse.

I can add some configuration options, but I'd like to know what is the alternate desired behavior when the situation arises.

**Comment by megavolkan** [comment]
Thanks for the answer. I think this is actually a bug because there are no duplicate files. One video file (xyz.avi) and a subtitle file (xyz.srt). Video and subtitle files obviously share the same name except the file extensions. Tvrenamer always renames subtitle files appended by a ~2 at the end of filename. Also if i use the "move" function of tvrenamer it places subtitle files under a "versions" folder  created by itself. This was not the default behaviour before. It happened after upgrading to 0.8 version. 
I use tvrenamer to rename and move my files along with subtitles so my media player app recognizes them correctly.
I was using Filebot app for my workflow but it was too cumbersome and needed too much user input in order to work. So i found tvrenamer and it worked brilliantly. I love the app but on it's current state it's no different from Filebot. 
I hope this can be worked around easily. At least if there is a detailed logging functionality we can find out why is this happening and apparently it's not happening for everyone but just for a couple of users like me.

**Comment by nextSAK** [comment]
I Agree.
Video file and subtitle file must have the same name, except file extension.
Hope this is not a big issue for you to correct, or give as an option.

I thank you in advance

**Comment by eprenamer** [comment]
OK, I've committed a change that will resolve this.  I'll try to get a release out pretty soon.

**Comment by vipuldelwadia** [comment]
Nice work @eprenamer !

**Comment by eprenamer** [comment]
I'm going to change the title string of the Issue.  Old title: "Versions folder upon move"
