### ISSUE TITLE
adds a ~2 to the end of the subtitle filename

### ISSUE THREAD

**Issue by nextSAK** [tvrenamer/tvrenamer#263]
I 'm opening a new issue
I'm using tvrenamer for renaming and moving both tv show file and subtitle files. 
After upgrading to v0.8 tvrenamer automatically appends **a "~2" to the end of the subtitle filename**.

No pervious versions had this problem

**Comment by megavolkan** [comment]
I have the same problem. Upon move app creates a "versions" folder and puts subtitle with "~2" appended to it.
 Is there a log file anywhere so we can track what's happening?

**Comment by eprenamer** [comment]
Sorry for the late response.  I did respond in #259 .  I'm going to close this as a duplicate.  Please provide any additional feedback in #259
