### ISSUE TITLE
episodes which are downloading information should not be selected

### ISSUE THREAD

**Issue by eprenamer** [tvrenamer/tvrenamer#311]
When we initially add an episode to the table, we don't yet know what the destination will be, or even if we'll be able to determine the destination.  Yet, we automatically check the checkbox as soon as we add it.  Later, if we can determine that we _don't_ know how to rename the file, we automatically uncheck it.

This seems a little backwards to me.  I think the items should initially be unchecked, and then become checked once we _do_ know what the destination should be.

**Comment by eprenamer** [comment]
@vipuldelwadia @daveharris Curious if you have any recollection why it was done this way originally.

**Comment by daveharris** [comment]
I assume because we were young, naive, optimistic developers who thought that things would work most of the time. Now we are beaten down from years of dealing with networks connections and know better!!! Don’t want to put words in @vipuldelwadia‘s mouth though, but I think he will agree with me

**Comment by eprenamer** [comment]
LOL fair enough!

**Comment by vipuldelwadia** [comment]
That's pretty much what I remember - we wanted to pre-check the rows as an optimisation, but at the time I didn't think about that kind of failure state. Makes sense though ;)

**Comment by eprenamer** [comment]
Resolved in #312
