### ISSUE TITLE
[BUG] Folder name with blank space when moving

### ISSUE THREAD

**Issue by devistar** [tvrenamer/tvrenamer#322]
I try to add a blank space at the end of folder name like this "Saison ". Then I apply but it's trimmed to "Saison". It doesn't save my change.

**Comment by rwgs** [comment]
I have also found this issue, please fix ASAP.

**Comment by eprenamer** [comment]
I assume this refers to the "Season Prefix", where we add the season number to the prefix.  So if you use "Saison ", you'll get folders like "Saison 1" (or "Saison 01", if you check the "leading zero" checkbox).

If that's the case this is resolved in 0.9b0.  If this refers to something else, please re-open.
