### ISSUE TITLE
Can't handle Seasons with 3 digits..

### ISSUE THREAD

**Issue by guideloom** [tvrenamer/tvrenamer#357]
When trying to rename shows that have season numbers over 99, The app fails... in fact., "nothing" even appears in the app window when dragging those episodes to it. No error. Nothing.

Example: ANY episode from "House Hunters International", starting in Season 100..
Create a file called "House Hunters International.S103E02.mkv" and drag into the app window to see.

**Comment by johnv02139** [comment]
FYI, you're running into Issue #99 where, when we could not parse a filename, we silently ignore it.  That Issue is resolved in the source code, but we haven't done a release since then.  We should be having one soon.

Once that is resolved, at least you'd see your filename, with a message saying "Did not extract show name from filename".

**Comment by johnv02139** [comment]
Then, onto your actual issue.  Yeah, I didn't imagine any shows had 100 seasons.  TV only started about 80 years ago!  I guess seasons don't always mean what I think they mean.

It's trivial to support this, in cases like your example.  One little hitch is that we tried to support other formats, including ones where there are no markers.  For example, "0609" would mean Season 6, Episode 9. 

But I think those formats are pretty dead.  I think it's ok to recognize a three-digit season when formatted unambiguously, and reject it in the less structured cases.

One other little thing is that we support zero-padding the season, which means we add a zero for seasons 1 - 9.  For shows with > 99 seasons, it will not produce the pleasing alignment that may be desired.  But I think that's probably ok, too.

**Comment by johnv02139** [comment]
The master branch is still using v1 of the TheTVDB API.  I've made a commit to master that gets it to work for the example filename you gave.  But it takes a really long time to parse all the episodes.  This should get much better when we upgrade to the v2 API.
