### ISSUE TITLE
Default lookup folder

### ISSUE THREAD

**Issue by reaves** [tvrenamer/tvrenamer#373]
Hello,

Would it be possible to add the possibility for TVRenamer to look at startup in a default folder, or to have an history of the latest folders scanned.

In any case, thanks a lot for your work !

**Comment by eprenamer** [comment]
Hi, both great suggestions.  If you are comfortable editing XML, there is already a way to set the startup folder, as partially described here:

https://github.com/tvrenamer/tvrenamer/wiki/Development-Setup#preloadfolder

If that is unclear, please let me know.  I do intend to expose that in a more user-friendly way in the near future.

As for the history of folders, I really hadn't thought of that, but it's a great suggestion.  Currently we have various "settings", and things like folder history _could_ go in there, but really it's more like "app data", which we don't currently maintain.  I do intend to add app data (and have already done so in a branch, but it still needs work).  I will try to add recent folder history once app data is there.

**Comment by reaves** [comment]
Hi, 
Indeed by editing the prefs.xml it's now loading a folder at startup.
Thanks for all
