### ISSUE TITLE
Not downloading show names

### ISSUE THREAD

**Issue by daveharris** [tvrenamer/tvrenamer#42]
#### What steps will reproduce the problem?
1. Opened Tv Renamer
2. Added shows
3. Says downloading
#### What is the expected output? What do you see instead?

To download the show name
Stuck on Downloading never gets the name of the show
#### What version of the product are you using? On what operating system?

0.5 os x 64bit

**Comment by eprenamer** [comment]
It looks like there was never anything to be done here.  Closing.
