### ISSUE TITLE
TvRenamer 0.5b3 crashes when 'TV' directory doesn't exist/inaccessible

### ISSUE THREAD

**Issue by daveharris** [tvrenamer/tvrenamer#44]
Mac OS X 10.6.7

Installed TVRenamer 0.5b3 three days ago. Worked perfectly! All episodes were renamed and moved to the correct location on the NAS. However, yesterday it all stopped working. TvRenamer won't startup anymore. I see the blinking icon on the Dock but after that it vanishes.

Java settings are :
JAVA SE6 (64 bit)
JAVA SE6 (32 bit)

First I re-installed the 0.5 version : no success. Secondly I Tried the 0.4 version : this one started up fine. 

Attached you will find the crash-report.

Cheers, Leon

**Comment by eprenamer** [comment]
This got resolved over a series of commits.  If the specified destination directory does not exist at startup, "move" is automatically disabled, the user sees a dialog box explaining the problem, and the program does not crash.
