### ISSUE TITLE
Colon very dangerous in windows filenames

### ISSUE THREAD

**Issue by daveharris** [tvrenamer/tvrenamer#46]
#### What steps will reproduce the problem?

Rename/move a tv episode for "Steven Seagal: Lawman"

The : (full colon) in windows is a sort of operator that directs file contents into an 'alternate stream'.

The upshot is that any files 'moved' to a path with a colon in it are actually hidden in an alternate stream (the stream's name being that portion to the right of the colon), and appear to be completely gone from a regular user's point of view. Windows does not show alternate streams anywhere.

I suggest implementing a path/name filter for windows and transcoding any invalid file/path characters (there must be one already right?). Set it to remove the : entirely or replace it with something else, perhaps - (dash)

I'm writing this for a friend. I can't say for certain if this applies to rename or move operations, or both. Either way you can't use a colon and shouldn't try.

This applies to v0.5b3 or whatever is current as of this date.

Thanks,
Sean

**Comment by vipuldelwadia** [comment]
I believe this has long been fixed
