### ISSUE TITLE
Issue scraping certain tv shows i.e. Pawn Stars, Street Customs Berlin

### ISSUE THREAD

**Issue by daveharris** [tvrenamer/tvrenamer#53]
#### What steps will reproduce the problem?
1. Add either later season 2 pawn stars or any street customs berlin episode to be renamed
#### What is the expected output? What do you see instead?

Expect output should be as followed
series name Season number and Episode number show title instead for Pawn Stars I get
Pawn Star$ incorrect season number and incorrect episode number
#### What version of the product are you using? On what operating system?

Version 0.5 for MAC
#### What is the result of running 'java -version' on the command line?

java version "1.6.0_29"
Java(TM) SE Runtime Environment (build 1.6.0_29-b11-402-10M3527)
Java HotSpot(TM) 64-Bit Server VM (build 20.4-b02-402, mixed mode)
#### Please provide any additional information below.

I've gotten a few errors with other different episodes but it returns the same thing.  Show name with $ and incorrect season and episode number.   Wish there was a force change.

**Comment by eprenamer** [comment]
It's after release 0.6, so closing.   :-)
