### ISSUE TITLE
Moar comments needed

### ISSUE THREAD

**Issue by ajdaniel** [tvrenamer/tvrenamer#67]
Just reimported the project onto my new pc, and looking again at UIStarter and it's a total wtf moment, could do with a bit of source code to identify some key methods, like renameFiles() with comments.

Perhaps not a single task, but something to consider as we add more changes.

As a side note, I am going to be adding some features I thought up of :D

**Comment by eprenamer** [comment]
Well, there are a lot moar comments now.  And a lot of reorganization.  Not sure if it satisfies @ajdaniel but I'm guessing he's not so concerned after four and a half years.  😃 

@ajdaniel Please feel free to let me know of any concerns if your interest in this project returns...
