### ISSUE TITLE
Error " Downloading show listings failed. Check internet connection" 

### ISSUE THREAD

**Issue by sdtheman** [tvrenamer/tvrenamer#71]
I get this error on multiple computers from multiple locations.

**Comment by Spaceherpe** [comment]
Looks like this issue has returned!  TVrage.com is down. Without this page, the program fails to function properly. 

Is this a temporary issue or is the program dead for good? I use this program almost daily, so I'm really hoping it comes back!

**Comment by daveharris** [comment]
It seems that they are trying ti fix it (
https://twitter.com/BenDrummond21/with_replies) but it's ridiculous that
it's been down for so long.

As @vipuldelwadia said in issue #88, we do have an experimental feature
using thetvdb.com. I'm ont entirely sure what the exact status of this in
or if it's even been released in beta format.

Given tvrage.com doesn't seem a stable, long-term solution so we should get
this sorted.

Dave

**Comment by vipuldelwadia** [comment]
I have just released a new beta (0.7b3) which changes the provider to TheTVDB. Please try this version and report back any issues you have.

Download: https://github.com/tvrenamer/tvrenamer/releases/tag/0.7b3
