### ISSUE TITLE
no useful feedback given when provider service is down

### ISSUE THREAD

**Issue by dbry23** [tvrenamer/tvrenamer#75]
Since May 12 or 13, anytime I add episodes to TVRenamer, I get a message "Downloading show listings failed. Check internet connection" instead of the proposed filename.
![screen shot 2014-05-15 at 6 54 01 pm](https://cloud.githubusercontent.com/assets/7597313/2991773/ea960be2-dc83-11e3-9cd0-32d35f28ce38.png)

**Comment by Spaceherpe** [comment]
I think this has happened again

**Comment by vipuldelwadia** [comment]
Looks like TheTVDB.com is down, which means that TVRenamer will not work until it comes back up. Unfortunately there is no status information anywhere so it's just a matter of checking it manually until it comes back up.

I'll leave this issue open as the tracker for TheTVDB.com being down, and will close it when the site is back.

**Comment by crashtestoz** [comment]
I think this issue is back. Getting "Downloading show listings failed. Check internet connection" on any file.

**Comment by Spaceherpe** [comment]
That would explain it! Thanks!

**Comment by eprenamer** [comment]
I modified the title.  Old title: "Episode names not downloading anymore"

**Comment by eprenamer** [comment]
I think #364 resolves this
