### ISSUE TITLE
Preference window is overcrowded

### ISSUE THREAD

**Issue by ajdaniel** [tvrenamer/tvrenamer#78]
I suggest moving some sections into tabs. The window is getting dangerously too tall to fit on my macbook air screen (1440x900)

**Comment by ajdaniel** [comment]
I've just committed this into my own feature branch with a couple of features. https://github.com/tvrenamer/tvrenamer/commit/1a8a6152b78b3319423ed5968eae611654969ae9

Screenshot:

![screen shot 2015-03-31 at 16 17 00](https://cloud.githubusercontent.com/assets/867941/6922194/65c41bd6-d7c1-11e4-80b4-3bd329d1ed3e.png)

**Comment by ajdaniel** [comment]
Fixed in 1a8a615

**Comment by daveharris** [comment]
+1 looks great!
