### ISSUE TITLE
"The 100" matches incorrectly as "The Mentalist"

### ISSUE THREAD

**Issue by 19wolf** [tvrenamer/tvrenamer#79]

**Comment by ajdaniel** [comment]
@vipuldelwadia is this bug fixed with your commit 489a2da?

**Comment by vipuldelwadia** [comment]
It should be, the test for that filename pattern is passing on master. I
didn't want to close the issue until we released a build with the fix.

**Comment by 19wolf** [comment]
I built a version myself (0.7 or something) and it worked fine.
