### ISSUE TITLE
"Destdir" encoding (accented chars) 

### ISSUE THREAD

**Issue by MrHeadwar** [tvrenamer/tvrenamer#80]
Hi, and thanks for this very usefull program.

I've tried to use the file moving option in the preferences, but my destination directory is accented ("D:\vidéo"). Although the .tvrenamer preferences file is utf8-encoded, the "é" char is garbage, so tvrenamer creates, on each launch, a "D:\vid%o" folder and places my files in it instead of the proper "Vidéo" folder. I suspect it has something to do either with the use of strings to store the value, or more probably with the .toXML (cf http://stackoverflow.com/questions/3642820/xstream-correct-way-to-save-xml-in-utf-8), although I don't know Java.

Regards

**Comment by daveharris** [comment]
Hi,
Thanks for getting in touch. That's an interesting bug and one we should fix.

Hopefully it's a quick fix by setting the content encoding.

To be honest development on this has pretty much ended since I've now become a rails developer and @vipuldelwadia has no time but we'll see what we can do.

Dave

**Comment by MrHeadwar** [comment]
So sad to read ! I like tv-renamer a lot : fast, simple, usefull, perfect for my needs.
Thanks anyway for your fast answer and for the program ! Maybe you could release a final 1.0 version with all the changes since 0.6 (and hopefully this bug fixed) ? 

Regards

**Comment by daveharris** [comment]
Thanks! Yeah it's pretty perfect for our needs - we've scratched our own itch. I still use it all the time to move files onto my NAS.

I'll have a chat to @vipuldelwadia this weekend about making a 1.0 (maybe we have a release party!) given that it basically does what we need it to. There are lots of outstanding bugs which makes me sad but I just have such little time these days (I'm trying to learn Japanese at the moment!)

Thanks for your comments, it's awesome that people get use out of it. When our tv listing provider (tvrage.com) changed their API, there was an outpouring of issues saying it was broken so I think it's actually used a lot more than we think it is!

**Comment by MrHeadwar** [comment]
Update : latest dev version compiled locally works :) Thanks !
