### ISSUE TITLE
Request: Allow ignore options

### ISSUE THREAD

**Issue by ajdaniel** [tvrenamer/tvrenamer#81]
I'd like to implement this myself but just putting it into the system. I'm annoyed about having to unselect media files that are SAMPLEs, and would like an option to ignore these. I was thinking a comma seperated list of ignores, so I can choose to ignore files that include sample, or .nfo. I imagine when adding a folder with these settings, it would add them to the list, but uncheck it automatically.

**Comment by daveharris** [comment]
Hi Andrew,
Sounds awesome, do it! Just create a new branch for the work and we'll think about what/when we want to release a new version.

As discussed in #80 maybe it's time we did a 1.0 release!

Dave

**Comment by ajdaniel** [comment]
New branch time!

**Comment by ajdaniel** [comment]
I just delivered this in the feature branch under commit 5dd6628. I will call for a merge request
