### ISSUE TITLE
Java classes advice

### ISSUE THREAD

**Issue by MrHeadwar** [tvrenamer/tvrenamer#82]
Hi,

I've been getting my feet wet with tvrenamer, and, as a low hanging fruit, I'm working on the "strip junk" function. I want the words not to be hardcoded but loaded from the config file, and user editable (some words are used in certain languages). I'm a total newbie in java, but copying from another parameter, I've already set the loading, saving, and UI of this new parameter, plus the function itself, BUT I run into a java problem : how can I import a parameter inside controller/util/stringutils ? I've moved removeLast and stripJunk in here, but stripjunk must access the parameter. Here's my stripJunk :
	1	public String stripJunk(String input) {
	2		String output = input;
	3		UserPreferences prefs = UserPreferences.getInstance();
	4		String junklist = prefs.getJunkWords();
	5		String[] junkwords = junklist.split(",");
	6		for(String s: junkwords) {
       	7			output = removeLast(output, s);
    	8		}
	9		return output;
	10	}
junklist is a comma separated list of words. My problem is : "non-static method stripJunk(String) cannot be referenced from a static context". 
What would you do ?

regards

**Comment by ajdaniel** [comment]
Hey @MrHeadwar thanks for taking an interest in the project! This sounds very similar to a feature I just implemented in commit 5dd6628 where certain keywords render a filename unchecked.
I don't understand your question though. Why do you want to import a 'parameter' (do you mean variable?) into StringUtils from TVRenamer.java?

**Comment by MrHeadwar** [comment]
Hi ! 
Well, my "feature" consisted in allowing the user to choose the keywords to start the in-string search for the show name / episode. It followed the [last commit](https://github.com/tvrenamer/tvrenamer/commit/489a2daf89dff6d81a33d959a8e47e93596958f6) by Vipul Delwadia : "Remove the random junk off the end of the filename before parsing it".
I've abandonned this feature : the getters and setters were OK, the function worked BUT no way to access my getJunkWords() function in StringUtils, and I don't know java so the classes inheritances, public/private static etc... are way beyond my understanding. 
Thanks anyway, for taking the time to answer and for this perfect little utility ! I hope you'll solve the issue #80 !

Regards
