### ISSUE TITLE
'Clear' button, and drag files to executable to open feature request [Type - Enhancement]

### ISSUE THREAD

**Issue by Paradoxum** [tvrenamer/tvrenamer#87]
After renaming some files, I have to always close the program and re-open it to add new ones because as far as I can tell there's no way to clear the list of items once added, a 'Clear' button would be nice.

Also, with another TV Renamer utility, I can drag a bunch of TV episodes onto the shortcut to the tool and the tool will open and the files will be added to the list to be renamed automatically, that doesn't seem to work with this one, the tool opens but the files are not added to the list to be renamed.

Anyway just some small suggestions, I really like the tool. Thanks.

I can't see any way for me to add the label "Type - Enhancement" anywhere, google says only contributors can add labels or something like that.

**Comment by daveharris** [comment]
Hi,

Thanks for letting us know about this, it annoys me too. Thankfully @MWGNZ has already fixed it in `v0.7b2`. You can grab the beta version from https://github.com/tvrenamer/tvrenamer/releases.

It is beta though so your milage may vary!

Dave

**Comment by Paradoxum** [comment]
Nice, thanks!
