### ISSUE TITLE
On Yosemite TVRenamer keeps saying unable to connect to internet

### ISSUE THREAD

**Issue by djkrimson** [tvrenamer/tvrenamer#88]
On Yosemite TVRenamer keeps saying unable to connect to internet. Even though there are no connection issues on the mac.

**Comment by NoelWalker** [comment]
I agree. I have tried it using Windows 7 and Linux and I get the same result.

**Comment by vipuldelwadia** [comment]
I believe that is the reason, I too cannot get to tvrage.com which is the provider we use for listings. We have an experimental version of tvrenamer which uses thetvdb.com for listings but it will require some effort to make a build of.

**Comment by vipuldelwadia** [comment]
I have just released a new beta (0.7b3) which changes the provider to TheTVDB. Please try this version and report back any issues you have.

Download: https://github.com/tvrenamer/tvrenamer/releases/tag/0.7b3

**Comment by NoelWalker** [comment]
The Windows version x86 seems to work ok now (using VirtualBox running Windows 7). 

I am having a problem running the Mac OS X 64 bit version however. After giving it permission to start it appears to start up then immediately shuts down again. My old version 0.6 still starts up ok.

**Comment by ChoznFlander** [comment]
What about using the API from TVMAZE?  http://www.tvmaze.com/api

**Comment by vipuldelwadia** [comment]
@NoelWalker 0.7b3 requires Java 8, which Java do you have installed?

**Comment by vipuldelwadia** [comment]
@ChoznFlander Good idea, I've opened a separate issue for it here: https://github.com/tvrenamer/tvrenamer/issues/89

**Comment by NoelWalker** [comment]
The Java I am using appears to be coming from my installation of Eclipse via Android Studio. I have installed Java JRE 8 from Oracle, but have yet to work out how to use that version instead of the Eclipse version.

**Comment by vipuldelwadia** [comment]
I believe there is a Java control panel you can use, accessed via the
System Preferences.

**Comment by NoelWalker** [comment]
Now working. Thank you for your help.

I had to install the JDK (instead of just the JRE) to change the Path. This is a quote from Oracle "Installing a JRE from Oracle will not update java -version symlinks or add java to your path. To be able to do this, you need to install the JDK." 

Cheers
