### ISSUE TITLE
0.7 crashes on launch with unknown error (Mac x64)

### ISSUE THREAD

**Issue by jakeopolis** [tvrenamer/tvrenamer#90]
Was running the most recent beta version, no problem. Updated to 0.7 and application crashes on launch with error message "The application "TVRenamer-0.7" can't be opened." Debug output is:
LSOpenURLsWithRole() failed with error -10810 for the file /Applications/TVRenamer-0.7.app.

Java version 8 build 60, OS 10.10.5. 

Thanks!

**Comment by megavolkan** [comment]
Exact same problem. OS X 10.10.5, with Java 8.60. Both 32 and 64Bit versions crashes with same error.

**Comment by vipuldelwadia** [comment]
We have identified an issue with the archives for OS X, can you please re-download the zip from https://github.com/tvrenamer/tvrenamer/releases/tag/0.7 ?

**Comment by jakeopolis** [comment]
Lovely, problem solved! Thanks :)

**Comment by crashtestoz** [comment]
Love the app. have been using the previous version without issue until the tvrage issue. Just tested the new 0.7 and still crashes on OS X 10.10.5. I tried both 64 and 32bit version. I get the following error:

19/09/2015 7:04:10.299 pm com.apple.xpc.launchd[1]: (com.google.code.tvrenamer.165320[402]) Service exited with abnormal code: 1

**Comment by megavolkan** [comment]
Same here. Crashing when run:
20.09.2015 14:44:09,222 com.apple.xpc.launchd[1]: (com.google.code.tvrenamer.162196[1754]) Service exited with abnormal code: 1

10.10.5 iMac, Java 8 Update 60, TVRenamer 0.7 64bit

**Comment by Makk1000** [comment]
I'm unable to launch the application at all
10.10.5 MacMini, Java 8 Update 60, TVRenamer 0.7 64bit/32bit

**Comment by crashtestoz** [comment]
Just tried the latest version and still getting the same error:

22/09/2015 4:07:07.381 pm com.apple.xpc.launchd[1]: (com.google.code.tvrenamer.166740[8742]) Service exited with abnormal code: 1

The application just will not start.
