### ISSUE TITLE
Version 0.7.1 Crashes on OSX 10.10.5

### ISSUE THREAD

**Issue by crashtestoz** [tvrenamer/tvrenamer#92]
I keep getting this error when trying to run the app. It crashes without even bringing up the file window.

22/09/2015 4:25:31.445 pm com.apple.xpc.launchd[1]: (com.google.code.tvrenamer.167024[11094]) Service exited with abnormal code: 1

**Comment by vipuldelwadia** [comment]
Ok, could you try the following in order please:
1. Ensure you've opened the app by the right-click -> open menu item, to get around Gatekeeper: https://github.com/tvrenamer/tvrenamer#tvrenamer-cant-be-opened-because-its-from-an-unidentified-developer-error-message-on-osx-mountain-lion-or-above
2. Ensure you have Java 7+ installed (check the Java control panel in the System Preferences)
3. Try deleting your tvrenamer preferences file (`/Users/<your username>/.tvrenamer`)
4. Run the program in debug mode: https://github.com/tvrenamer/tvrenamer#running-in-debug-mode

**Comment by crashtestoz** [comment]
1. Downloaded a fresh version 0.7.1 from the link provided.
2. In System Preferences / Genreal /I enable Allow apps download from: Anywhere
3. Running Java version 8 update 60
4. Deleted (/Users/<your username>/.tvrenamer)
5. Tried to run run-mac.sh but that didn't seem to do anything
6. Tried running the tvrenamer.jar file with java -jar <file> got the following:
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/google/code/tvrenamer/view/UIStarter : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)

7. Right-click Open without Gatekeeper gives the same error:

22/09/2015 6:14:33.065 pm com.apple.xpc.launchd[1]: (com.google.code.tvrenamer.169012[1082]) Service exited with abnormal code: 1

**Comment by vipuldelwadia** [comment]
Ok, the result of 6 suggests that you have more than one Java installed, and that the default Java is too low version. What does `java -version` say?

**Comment by crashtestoz** [comment]
hmm very interesting ...
java -version
java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-466.1-11M4716)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-466.1, mixed mode)

However in System Preferences the Java app says its version 8 update 60

**Comment by vipuldelwadia** [comment]
I believe if you follow this it should work: http://superuser.com/a/587963

**Comment by crashtestoz** [comment]
I removed the old JDK as per the link. Running TVRenamer now asks for JRE ??? JRE is installed and is accessible in the System Preferences ... do I need to reinstall from https://www.java.com/en/download/mac_download.jsp

**Comment by vipuldelwadia** [comment]
If `/Library/Java/JavaVirtualMachines` is empty then I would suggest reinstalling Java from that link https://www.java.com/en/download/mac_download.jsp

**Comment by crashtestoz** [comment]
1. Uninstalled previous Java following: https://www.java.com/en/download/help/mac_uninstall_java.xml
2. Restarted
3. Reinstalled Java from https://www.java.com/en/download/mac_download.jsp
4. Running TVRename brings up a window that I need Java Run Time Environment installed ...

Do I need JDK? none of the java command line options are available without it.

**Comment by crashtestoz** [comment]
Installing JDK now, I found this:
As per Oracle's JRE installation document

Installing a JRE from Oracle will not update java -version symlinks or add java to your path. To be able to do this, you need to install the JDK.
The Oracle JDK does change /usr/bin/java to point to the Java 7 executable. If you are doing development then you should use this as it includes more than the JRE.

The Oracle install FAQ says

Q: Should I install the JRE or the JDK?

A: If you plan to run Java applications, install the Java Runtime Environment (JRE). The JRE is also referred to as Oracle Java. Once you have installed the JRE, you can launch Java applets and applications by double-clicking JAR files, JNLP files, and via the browser. Note that 32-bit browsers, such as Firefox in 32-bit mode, and Chrome, are not supported by the JRE.

If you plan to write Java applications, install the Java Development Kit (JDK).

**Comment by crashtestoz** [comment]
After installing the JDK the app works ... do I really need JDK to run TVRenamer?

**Comment by Makk1000** [comment]
It was the only way I got my TVNamer 0.7.1 to work

**Comment by vipuldelwadia** [comment]
Hey guys,

Can you please give this version a shot: https://github.com/tvrenamer/tvrenamer/releases/tag/0.7.2b1

It should not require a JDK to be installed, and will work with just the JRE.

**Comment by crashtestoz** [comment]
I can confirm that 0.7.2b1 works well on OS X 10.10.5 without JDK installed. Love your work.

I know this belongs to a feature request group but have you thought about letting TVRenamer run in the background and automatically rename and move files that show up in a certain folder?

**Comment by daveharris** [comment]
Hi,
Glad that it's now working. We have a very long-standing enhancement (#34). @vipuldelwadia has had a go at getting this working, but that was a long time ago. Agreed it would be very useful though.

Thanks to @vipuldelwadia for fixing the release!

@vipuldelwadia, we should close this when we release 0.7.2

**Comment by eprenamer** [comment]
Looks like this should have been closed already.  Closing it now.
