### ISSUE TITLE
Grouping of files

### ISSUE THREAD

**Issue by kekePower** [tvrenamer/tvrenamer#98]
Hi.

Would it be possible to add an option to add 'a' or '.1' to the formatting options?

This is for grouping of movies or tv series that are split up in different files.

Cheers,
kekePower

**Comment by eprenamer** [comment]
How would you want the program to determine when to add a 'a' or '.1'?  Do you mean whenever there is a conflict?

**Comment by eprenamer** [comment]
Unfortunately this request is not clear to me.  I'm closing it, but anyone who has this issue, feel free to re-open.
